name: Validate Nix Flake & SPO Scripts

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'   # Trigger workflow for version tags
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Nix with flakes
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # TODO: Fix cache if possible
      # - name: Cache Nix store
      #   uses: actions/cache@v4
      #   with:
      #     path: /nix/store
      #     key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nix-

      - name: Validate all networks
        run: |
          for network in default mainnet preprod preview; do
            echo "=== Testing flake environment: $network ==="
            nix develop --accept-flake-config .#${network} --command bash 00_common.sh
          done

  publish_release:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release generated from GitHub Actions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
